# Tolep Coy
# Kalo bingung chat ane aja
# Di https://facebook.com/tolepcoymalmsteen
name: SL Scan

# Pikirlah dewek ini untuk apo
on: push

jobs:
  Scan-Build:
    # Scan runs di ubuntu, mac atau windows
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    # Instruksi
    # 1. Setup JDK, Node.js, Python atau apo bae
    # 2. Compile atau build project sebelum scan
    #    Contoh: mvn compile, atau npm install atau pip install disini
    # 3. Invoke Scan pake github token.

    - name: Perform Scan
      uses: ShiftLeftSecurity/scan-action@master
      env:
        WORKSPACE: ""
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SCAN_AUTO_BUILD: true
      with:
        output: reports
        # Scan auto-detects untuk bahasa.
        # type: credscan,java
        # type: python

    - name: Upload report
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: reports
